version: 2.1
orbs:
 acunetix360: acunetix-360/acunetix-360@1.0.0
workflows:
  scan-workflow:
    jobs:
      - acunetix360/scan:
          website_id: cc4db2b4-2e44-4028-df47-ab5201639d1d
          api_url: https://online.acunetix360.com/
          scan_type: FullWithPrimaryProfile

